# Generated by Django 3.1.7 on 2021-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210225_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.CharField(default='No detail', max_length=3000, verbose_name='Task Details'),
            preserve_default=False,
        ),
    ]
